// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace handover_api.Models
{
    [Table("annouce_reader")]
    [Index("ReaderId", Name = "ReaderID_UNIQUE", IsUnique = true)]
    public partial class AnnouceReader
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        /// <summary>
        /// PK(GUID)
        /// </summary>
        [Column("ReaderID")]
        [StringLength(100)]
        public string ReaderId { get; set; }
        /// <summary>
        /// announcement.AnnounceID
        /// </summary>
        [Column("AnnounceID")]
        [StringLength(100)]
        public string AnnounceId { get; set; }
        /// <summary>
        /// member.UserID
        /// </summary>
        [Column("UserID")]
        [StringLength(100)]
        public string UserId { get; set; }
        public bool? IsRead { get; set; }
        [StringLength(45)]
        public string ReadTime { get; set; }
        public bool? IsActive { get; set; }
    }
}