// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace handover_api.Models;

[Table("category_item")]
public partial class CategoryItem
{
    [Key]
    [StringLength(100)]
    public string ItemId { get; set; } = null!;

    [StringLength(100)]
    public string CategoryId { get; set; } = null!;

    /// <summary>
    /// FixedComment,DynamicComment,Selection,SelectionWithTable,Table,RemarkWithVerify
    /// </summary>
    [StringLength(45)]
    public string ItemType { get; set; } = null!;

    [StringLength(1000)]
    public string? ItemTitle { get; set; }

    [StringLength(45)]
    public string? ItemWidth { get; set; }

    [Column(TypeName = "json")]
    public string? ItemOption { get; set; }
}