// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace handover_api.Models;

[Table("handover_detail_handlers")]
public partial class HandoverDetailHandler
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [StringLength(100)]
    public string HandoverDetailId { get; set; } = null!;

    [StringLength(45)]
    public string UserId { get; set; } = null!;

    [StringLength(45)]
    public string UserName { get; set; } = null!;

    [StringLength(300)]
    public string? Remarks { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime? SubmitTime { get; set; }

    /// <summary>
    /// HANDOVER(交班者),TAKEOVER(接班者)
    /// </summary>
    [StringLength(45)]
    public string Type { get; set; } = null!;
}