// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace handover_api.Models
{
    /// <summary>
    /// 交班表設定主表
    /// </summary>
    [Table("handover_sheet_main")]
    [Index("SheetId", Name = "SheetID_UNIQUE", IsUnique = true)]
    public partial class HandoverSheetMain
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("SheetID")]
        [StringLength(100)]
        public string SheetId { get; set; }
        [StringLength(100)]
        public string Title { get; set; }
        [StringLength(100)]
        public string Description { get; set; }
        [StringLength(2000)]
        public string Image { get; set; }
        [Column(TypeName = "timestamp")]
        public DateTime? CreatedOn { get; set; }
        [Column(TypeName = "timestamp")]
        public DateTime? ModifiedOn { get; set; }
        public bool? IsActive { get; set; }
        [StringLength(45)]
        public string Version { get; set; }
        [StringLength(100)]
        public string SerialCode { get; set; }
        [StringLength(100)]
        public string CreatorName { get; set; }
    }
}